name: todo_app
description: "Ứng dụng quản lý công việc Todo App - Flutter + PHP + MySQL"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.2

  # Network
  dio: ^5.4.3

  # Local storage
  shared_preferences: ^2.2.3

  # Routing
  go_router: ^14.2.0

  # UI helpers
  intl: ^0.19.0
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
